TYPO3:
  Neos:
    typoScript:
      autoInclude:
        'Jonnitto.NodeTypes': TRUE
    userInterface:
      translation:
        autoInclude:
          'Jonnitto.NodeTypes': ['NodeTypes/*']

Jonnitto:
  NodeTypes:
    Headline:
      defaultTagName: h2
    Button:
      defaultClassName: btn
      defaultStyle: secondary
    Image:
      maximumWidth: 2560
      maximumHeight: 1440
      openOriginalImageInLightbox: FALSE
      renderRetina: TRUE
      lightbox:
        class: 'lightbox'
        target: '_blank'
    container: container
    instanceOfDocument: '[instanceof TYPO3.Neos:Document]'
    externalTarget: '_blank'
