
Jonnitto:
  NodeTypes:
    Headline:
      firstTagName: h1
      defaultTagName: h2
    Button:
      defaultClassName: btn
      defaultStyle: secondary
      groupClassName: btn-group
    Image:
      inlineSVG: true
      maximumWidth: 1440
      maximumHeight: 1280
      bleedWidth: 1920
      bleedHeight: 1680
      openOriginalImageInLightbox: false
      renderRetina: true
      lightbox:
        class: lightbox
        target: _blank
    Notification:
      alert: 'background:#d9534f;'
      warning: 'background:#f0ad4e;'
      info: 'background:#5bc0de;'
      style: 'color:#fff;box-shadow:0 1px 10px rgba(0,0,0,0.1);padding:5% 12px;margin:30px auto;text-align:center;text-decoration:none;outline:none;font-size:20px;'
    container: false
    containerFluid: false
    instanceOfDocument: '[instanceof Neos.Neos:Document]'
    prependIdentifier: id-
    externalTarget: _blank
    assetExternal: 'image,video,pdf'
    assetlist:
      thumbnail:
        width: 200
Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          Jonnitto.NodeTypes:
            - 'NodeTypes/*'
    nodeTypes:
      groups:
        special:
          position: 400
          label: 'Jonnitto.NodeTypes:NodeTypes.Groups:special'
          collapsed: true
    fusion:
      autoInclude:
        Jonnitto.NodeTypes: true
