TYPO3:
  Neos:
    typoScript:
      autoInclude:
        'Jonnitto.NodeTypes': TRUE
    userInterface:
      translation:
        autoInclude:
          'Jonnitto.NodeTypes': ['NodeTypes/*']
    nodeTypes:
      groups:
        special:
          position: 400
          label: 'Jonnitto.NodeTypes:NodeTypes.Groups:special'

Jonnitto:
  NodeTypes:
    Headline:
      firstTagName: h1
      defaultTagName: h2
    Button:
      defaultClassName: btn
      defaultStyle: secondary
    Image:
      maximumWidth: 2560
      maximumHeight: 1440
      openOriginalImageInLightbox: FALSE
      renderRetina: TRUE
      lightbox:
        class: 'lightbox'
        target: '_blank'
    Notification:
      alert: 'background:#d9534f;'
      warning: 'background:#f0ad4e;'
      info: 'background:#5bc0de;'
      style: 'color:#fff;box-shadow: 0 1px 10px rgba(0,0,0,0.1);padding:5% 12px;margin:30px auto;text-align:center;text-decoration:none;outline:none;font-size:20px;'
    container: container
    containerFluid: container-fluid
    instanceOfDocument: '[instanceof TYPO3.Neos:Document]'
    externalTarget: '_blank'
